### ISSUE TITLE
Not in the Elm package index

### ISSUE THREAD

**Issue by rhofour** [newlandsvalley/elm-binary-base64#1]
Is there any reason this isn't in the elm package index?

I'm looking to use this when encoding MIDI data and it'd be nice to be able to depend on it directly.

**Comment by newlandsvalley** [comment]
Yes - a rather big reason - it doesn't work.  There's _still_ no support for binary data in Elm.  See, for example, this issue - https://groups.google.com/forum/#!topic/elm-discuss/spr621OlUeo.  I wrote this ages ago again in the naive expectation that it would soon be sorted out.

**Comment by rhofour** [comment]
Yeah, I was thinking it might be nice to use until there's official support though. Especially for encoding a list of "bytes" into a string. However, I've discovered I don't really need it for what I want to do.

I share your frustration with the lack of binary support. It seems Elm isn't well setup to handle any new features of the web.

**Comment by newlandsvalley** [comment]
Well, I left it here in case someone needed to do something like that, but it's so awkward isn't it?  Personally, I feel that a binary data type is necessary in order to wrap many of the web-platform APIs -
 progress here, too, has been glacially slow.  This is the main reason why I reluctantly decided to abandon Elm.

**Comment by ymtszw** [comment]
Hi, let me jump in to this case.

I have actually done (and am doing) something meaningful using your `BinaryBase64` implementation.
Namely, it is [AWS V2 signing](http://docs.aws.amazon.com/general/latest/gr/signature-version-2.html).

You may know that V2 signing is basically outdated and no longer used for newer AWS regions/services,
but there is still a particular remaining use case for this method, that is, [Product Advertising API][paapi] (PAAPI).

[paapi]: http://docs.aws.amazon.com/AWSECommerceService/latest/DG/Query_QueryAuth.html

PAAPI is not strictly an AWS service, but rather, API of Amazon Affiliate Program of Amazon E-Commerce.

I'm currently experimenting around using PAAPI from headless Elm, naturally leading me to implement necessary V2 signing.
V2 signing involves HMAC SHA256 calculation and binary-to-base64 conversion,
in that process your `BinaryBase64` served the role nicely! Yeah! Thanks!

Here's current implementation => https://github.com/ymtszw/blaze/blob/525ef12df13aa86cf3d9c5670d0498c4143cf31f/src/PAAPI.elm#L149
And tests => https://github.com/ymtszw/blaze/blob/525ef12df13aa86cf3d9c5670d0498c4143cf31f/tests/PAAPITest.elm#L14

It combines:

- [`ktonon/elm-crypto`](http://package.elm-lang.org/packages/ktonon/elm-crypto/latest)
- [`ktonon/elm-word`](http://package.elm-lang.org/packages/ktonon/elm-word/latest)
- `BinaryBase64`, including it via git-submodule

So at least, there is an use case for your `BinaryBase64` even in current context!
I am very happy if you publish this as Elm package so I can use it without git-submodule.
(And perhaps, extract AWS V2 signing part into separate package.)

**Comment by newlandsvalley** [comment]
I'm amazed!  OK - when I get a little time I'll have a look at how you're using it and see about publishing it.

**Comment by newlandsvalley** [comment]
Many thanks for your comments and code sample, @ymtszw .  I can see that if you're only encoding, then it is a bit more use.  Now published to the package index as requested.
