### ISSUE TITLE
Namespace maintenance

### ISSUE THREAD

**Issue by pravdomil** [newlandsvalley/elm-binary-base64#10]
Hi, do you think that you can rename your module from "BinaryBase64" to "Base64.Binary" to align with other Base64 packages?

<img src="https://user-images.githubusercontent.com/2387356/113860391-43099980-97a6-11eb-9e69-9cd57a74396f.png" width="256">

**Comment by newlandsvalley** [comment]
I see no reason at all to do this.  As far as I am aware, module names are a matter of personal choice and I prefer to keep the name as it is,  I also would not wish to introduce a breaking change for a non-essential reason such as this.

**Comment by pravdomil** [comment]
So the reason was to group all modules together based on their names to easily find packages.

I have made exception for your package and put it into Base64 group.

Now you can find Base64 related modules together on https://elm.pravdomil.com/packages/ (group by modules and search "base").

<img src="https://user-images.githubusercontent.com/2387356/114026078-1e7cf280-9876-11eb-8a48-e92610a96c82.png" width="256">

**Comment by newlandsvalley** [comment]
OK - thanks.  I guess users might be better off selecting a Base64 library that is more actively maintained.
