### ISSUE TITLE
Support Elm-0.19.0

### ISSUE THREAD

**Issue by ShrykeWindgrace** [newlandsvalley/elm-binary-base64#6]
Hi!

Do you per chance have any plans to upgrade this package to `elm-0.19.0`?

**Comment by newlandsvalley** [comment]
Not personally, but I've handed over support to @justgook - he may well be interested.

**Comment by justgook** [comment]
Im little bit out of elm for few weeks, will back soon - so then will start porting all that stuff..
And already have ported it, but not published - need to recheck tests..

**Comment by newlandsvalley** [comment]
Many thanks @justgook.

**Comment by ShrykeWindgrace** [comment]
@justgook @newlandsvalley thanks a lot!

**Comment by 4onen** [comment]
So this PR's useless. Sorry! I'll just go away now.

**Comment by newlandsvalley** [comment]
No not useless at all - thanks for the PR.  However, I'll defer to @justgook to decide how to proceed. By the way, I'm British, and we use _Licence_ over here - but perhaps this spelling may confuse some software - I'm not sure.

**Comment by 4onen** [comment]
My mistake. I had never seen that spelling of License before, so I just assumed it was a typo. Thanks for the tip!

I doubt my PR has any groundbreaking ideas for how to better port a package, but do with it as you will.

**Comment by justgook** [comment]
@4onen  i leaved few comments, can you fix those and reapply PR?

**Comment by 4onen** [comment]
Apologies for my ignorance @justgook but I can't seem to find the comments. Where on Github should I be looking for them?

**Comment by justgook** [comment]
@4onen  inside PR - there is possible leave comments for [review](https://github.com/newlandsvalley/elm-binary-base64/pull/7)

**Comment by justgook** [comment]
btw - You can find me in Slack as `@Kalabibishkis`
